//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char inv2a8x8 [] = {
0x7E, 0x99, 0x99, 0x7E, 0x24, 0x3C, 0x24, 0x24, 
};
