//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char inv3b8x8 [] = {
0x1E, 0xFB, 0xFF, 0x1B, 0x3C, 0x3C, 0x54, 0x0B, 
};
