//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char inv3a8x8 [] = {
0xFE, 0x17, 0xFF, 0x18, 0x7E, 0x9D, 0x04, 0x3B, 
};
