//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char inv4b8x8 [] = {
0x4A, 0x3C, 0x34, 0x6A, 0xB5, 0x3C, 0x5A, 0x24, 
};
