//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char inv4a8x8 [] = {
0x52, 0x3C, 0xAD, 0x56, 0x2C, 0xBD, 0x5A, 0x18, 
};
