//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char alien1a [] = {
0x20, 0x10, 0x3F, 0x6F, 0xFF, 0xBF, 0xA0, 0x19, 0x80, 0x00, 0x00, 0x00, 
};
