//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char alien1b [] = {
0x20, 0x90, 0xBF, 0xEF, 0xFF, 0x7F, 0x20, 0x40, 0x20, 0x00, 0x00, 0x00, 
};
